- name: check if we need to build
  stat:
    path: "{{ curl_install_directory }}/lib/libcurl.a"
  register: _libcurl_a

- include: build.yml
  when: not _libcurl_a.stat.exists or force_rebuild

- name: append to PKG_CONFIG_PATH
  set_fact:
    pkg_config_path: "{{ pkg_config_path|default([]) + [curl_install_directory + '/lib/pkgconfig'] }}"
