- name: check if we need to build
  stat:
    path: "{{ zstd_install_directory }}/lib/libzstd.a"
  register: _libzstd_a

- include: build.yml
  when: not _libzstd_a.stat.exists or force_rebuild

- name: append to PKG_CONFIG_PATH and PATH
  set_fact:
    pkg_config_path: "{{ pkg_config_path|default([]) + [zstd_install_directory + '/lib/pkgconfig'] }}"
