- name: check if we need to build
  stat:
    path: "{{ sqlite3_install_directory }}/lib/libsqlite3.a"
  register: _sqlite3_a

- include: build.yml
  when: not _sqlite3_a.stat.exists or force_rebuild

- name: append to PKG_CONFIG_PATH and PATH
  set_fact:
    pkg_config_path: "{{ pkg_config_path|default([]) + [sqlite3_install_directory + '/lib/pkgconfig'] }}"
