- name: check if we need to build
  stat:
    path: "{{ icu_install_directory }}/lib/libicui18n.a"
  register: _libicui18n_a

- include: build.yml
  when: not _libicui18n_a.stat.exists or force_rebuild

- name: append to PKG_CONFIG_PATH and PATH
  set_fact:
    pkg_config_path: "{{ pkg_config_path|default([]) + [icu_install_directory + '/lib/pkgconfig'] }}"
    path: "{{ [icu_install_directory + '/bin'] + path|default([]) }}"
    cflags: "{{ cflags|default([]) + ['-DU_STATIC_IMPLEMENTATION'] }}"

