- name: remove old install/build directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ libzip_build_directory }}"
  - "{{ libzip_install_directory }}"

- name: create required directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ libzip_source_directory }}"
  - "{{ libzip_build_directory }}"
  - "{{ libzip_install_directory }}"

- name: download
  git:
    repo: https://github.com/nih-at/libzip
    depth: 1
    version: "{{ libzip_version }}"
    dest: "{{ libzip_source_directory }}"

- name: check if we need to run autogen
  stat:
    path: "{{ libzip_source_directory }}/configure"
  register: _libzip_configure

- name: configure libzip
  command: >-
    cmake
    -DCMAKE_INSTALL_PREFIX={{ libzip_install_directory }}
    {{ libzip_configure_flags }}
    {{ libzip_source_directory }}
  args:
    chdir: "{{ libzip_build_directory }}"

- name: make libzip
  command: make -j10 install
  args:
    chdir: "{{ libzip_build_directory }}"
