- name: remove old install/build directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ libbrotli_build_directory }}"
  - "{{ libbrotli_install_directory }}"

- name: create required directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ libbrotli_source_directory }}"
  - "{{ libbrotli_build_directory }}"
  - "{{ libbrotli_install_directory }}"

- name: download
  git:
    repo: https://github.com/bagder/libbrotli
    depth: 1
    recursive: true
    version: "{{ libbrotli_version }}"
    dest: "{{ libbrotli_source_directory }}"

- name: autogen
  shell: ./autogen.sh
  args:
    creates: configure
    chdir: "{{ libbrotli_source_directory }}"

- name: configure libbrotli
  command: >
    {{ libbrotli_source_directory }}/configure
    --prefix={{ libbrotli_install_directory }}
    {{ libbrotli_configure_flags }}
  args:
    chdir: "{{ libbrotli_build_directory }}"

- name: make libbrotli
  command: make -j10 install
  args:
    chdir: "{{ libbrotli_build_directory }}"
