- name: check if we need to build
  stat:
    path: "{{ libbrotli_install_directory }}/lib/libbrotlidec.a"
  register: _libbrotlidec_a

- include: build.yml
  when: not _libbrotlidec_a.stat.exists or force_rebuild

- name: append to PKG_CONFIG_PATH and PATH
  set_fact:
    pkg_config_path: "{{ pkg_config_path|default([]) + [libbrotli_install_directory + '/lib/pkgconfig'] }}"
    ldflags: "{{ ldflags|default([]) + ['-L' + libbrotli_install_directory + '/lib'] }}"
