libzip_version: v1.7.3
libzip_source_directory: "{{ source_directory }}/libzip-{{ libzip_version }}"
libzip_build_directory: "{{ build_directory }}/libzip-{{ libzip_version }}"
libzip_install_directory: "{{ install_directory }}/libzip-{{ libzip_version }}"

libzip_configure_flags: >
  -DBUILD_SHARED_LIBS=OFF
  -DENABLE_COMMONCRYPTO=OFF
  -DENABLE_MBEDTLS=OFF
  -DENABLE_GNUTLS=OFF
  -DENABLE_OPENSSL=ON
  -DBUILD_EXAMPLES=OFF
  -DBUILD_DOC=OFF
  -DBUILD_TOOLS=OFF
  -DENABLE_BZIP2=ON
  -DENABLE_LZMA=ON
