- name: remove old install/build directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ libwebp_build_directory }}"
  - "{{ libwebp_install_directory }}"

- name: create required directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ libwebp_source_directory }}"
  - "{{ libwebp_build_directory }}"
  - "{{ libwebp_install_directory }}"

- name: download
  git:
    repo: https://chromium.googlesource.com/webm/libwebp
    depth: 1
    version: "{{ libwebp_version }}"
    dest: "{{ libwebp_source_directory }}"


- name: check if we need to run autogen
  stat:
    path: "{{ libwebp_source_directory }}/configure"
  register: _libwebp_configure

- name: autogen
  command: ./autogen.sh
  args:
    chdir: "{{ libwebp_source_directory }}"
  when: not _libwebp_configure.stat.exists

- name: configure libwebp
  command: >
    {{ libwebp_source_directory }}/configure
    --prefix={{ libwebp_install_directory }}
    {{ libwebp_configure_flags }}
  args:
    chdir: "{{ libwebp_build_directory }}"

- name: make libwebp
  command: make -j10 install
  args:
    chdir: "{{ libwebp_build_directory }}"
