- name: remove old install/build directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ freetype2_build_directory }}"
  - "{{ freetype2_install_directory }}"

- name: create required directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ freetype2_source_directory }}"
  - "{{ freetype2_build_directory }}"
  - "{{ freetype2_install_directory }}"

- name: download
  git:
    repo: git://git.sv.nongnu.org/freetype/freetype2.git
    depth: 1
    version: "{{ freetype2_version }}"
    dest: "{{ freetype2_source_directory }}"
  register: _freetype2_git_clone

- name: force autogen when repo is changed
  command: ./autogen.sh
  args:
    chdir: "{{ freetype2_source_directory }}"
  when: _freetype2_git_clone is changed

- name: configure freetype2
  command: >
    {{ freetype2_source_directory }}/configure
    --prefix={{ freetype2_install_directory }}
    {{ freetype2_configure_flags }}
  args:
    chdir: "{{ freetype2_build_directory }}"

- name: make freetype2
  command: make -j10 install
  args:
    chdir: "{{ freetype2_build_directory }}"
