- name: check if we need to build
  stat:
    path: "{{ freetype2_install_directory }}/lib/libfreetype.a"
  register: _libfreetype_a

- include: build.yml
  when: not _libfreetype_a.stat.exists or force_rebuild

- name: append to PKG_CONFIG_PATH and PATH
  set_fact:
    pkg_config_path: "{{ pkg_config_path|default([]) + [freetype2_install_directory + '/lib/pkgconfig'] }}"
