- name: check if we need to build
  stat:
    path: "{{ libxml2_install_directory }}/lib/libxml2.a"
  register: _libxml2_a

- include: build.yml
  when: not _libxml2_a.stat.exists or force_rebuild

- name: append to PKG_CONFIG_PATH
  set_fact:
    pkg_config_path: "{{ pkg_config_path|default([]) + [libxml2_install_directory + '/lib/pkgconfig'] }}"
