- name: remove old install/build directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ libidn2_build_directory }}"
  - "{{ libidn2_install_directory }}"

- name: create required directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ libidn2_source_directory }}"
  - "{{ libidn2_build_directory }}"
  - "{{ libidn2_install_directory }}"

- name: download
  git:
    repo: https://gitlab.com/libidn/libidn2.git
    depth: 1
    version: "{{ libidn2_version }}"
    dest: "{{ libidn2_source_directory }}"

- name: check if we need to bootstrap
  stat:
    path: "{{ libidn2_source_directory }}/configure"
  register: _libidn2_configure

- name: bootstrap
  command: ./bootstrap
  args:
    chdir: "{{ libidn2_source_directory }}"
  when: not _libidn2_configure.stat.exists

- name: configure libidn2
  command: >
    {{ libidn2_source_directory }}/configure
    --prefix={{ libidn2_install_directory }}
    {{ libidn2_configure_flags }}
  args:
    chdir: "{{ libidn2_build_directory }}"

- name: copy required files from source to build
  copy:
    src: "{{ libidn2_source_directory }}/{{ item }}"
    dest: "{{ libidn2_build_directory }}/{{ item }}"
    remote_src: true
  with_items:
  - lib/idna-tables-properties.csv


- name: make libidn2
  command: make -j10 install
  args:
    chdir: "{{ libidn2_build_directory }}"
