curl_version: curl-7_73_0
curl_source_directory: "{{ source_directory }}/{{ curl_version }}"
curl_build_directory: "{{ build_directory }}/{{ curl_version }}"
curl_install_directory: "{{ install_directory }}/{{ curl_version }}"

curl_configure_flags: >
  --disable-shared
  --enable-static
  --disable-debug
  --enable-optimize
  --enable-warnings
  --disable-curldebug
  --enable-symbol-hiding
  --with-ssl
  --with-zstd
  --with-brotli
  --disable-ares
  --disable-ech
  --enable-http
  --enable-ftp
  --enable-file
  --enable-tftp
  --enable-pop3
  --enable-imap
  --enable-smtp
  --enable-proxy
  --disable-ldap
  --disable-ldaps
  --disable-rtsp
  --enable-dict
  --enable-telnet
  --disable-smb
  --disable-gopher
  --disable-mqtt
  --disable-manual
  --disable-libcurl-option
  --enable-ipv6
  --disable-openssl-auto-load-config
  --disable-versioned-symbols
  --disable-threaded-resolver
  --enable-pthreads
  --enable-rt
  --enable-verbose
  --disable-sspi
  --disable-crypto-auth
  --disable-ntlm-wb
  --enable-unix-sockets
  --enable-cookies
  --enable-socketpair
  --enable-http-auth
  --disable-doh
  --enable-mime
  --enable-dateparse
  --disable-netrc
  --enable-progress-meter
  --enable-dnsshuffle
  --enable-get-easy-options
  --enable-alt-svc
  --without-librtmp
  --with-nghttp2
