- name: check if we need to build
  stat:
    path: "{{ tidy_html5_install_directory }}/lib/libtidy.a"
  register: _libtidy_a

- include: build.yml
  when: not _libtidy_a.stat.exists or force_rebuild

- name: append to PKG_CONFIG_PATH and PATH
  set_fact:
    pkg_config_path: "{{ pkg_config_path|default([]) + [tidy_html5_install_directory + '/lib/pkgconfig'] }}"
